### ISSUE TITLE
ブログ記事一覧ページにおける1, 2記事目の高さが不自然

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb#1]
1. デザイン案における3記事並びならともかく、2記事だと不自然感がある
2. タブレット版表示の際に記事高さがかなり不自然になる

![20210319-235342-firefox-LxSGBgdLId](https://user-images.githubusercontent.com/8929706/111799481-657a6680-890e-11eb-9d70-bbca4879761d.png)
![image](https://user-images.githubusercontent.com/8929706/111799459-5eebef00-890e-11eb-8f1b-3063896aa800.png)

**Comment by Hiratake** [comment]
こんなかんじでそろえます
![image](https://user-images.githubusercontent.com/23224932/111800888-be96ca00-890f-11eb-85db-06c7d4f823a9.png)

**Comment by book000** [comment]
1記事目を目立たせる案はよいと思うけど、それで2記事目が不自然になってしまうとちょっとね。もし目立たせることを出来る状態下で綺麗になればいいのだけど

**Comment by Hiratake** [comment]
1記事目をもっと大きくして2記事目を2段目に持っていくことも考えたけど、どうせアイキャッチ画像がデフォ画像ばっかりになるから微妙だなというお気持ち。
