### ISSUE TITLE
ヘッダー項目の修正

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb#13]
[jaoweb-docs](https://github.com/jaoafa/jaoweb-docs) の記事配置に合わせるため、いくつかの項目を修正

## パスの変更

- 方針: `/server/policys` → `/server/policies`
- プライバシーポリシー: `/server/privacy` → `/server/policies/privacy`

## 名称の変更

- 鉄道敷設に関するガイドライン → 鉄道・道路敷設に関するガイドライン
- 撮影・動画配信に関するガイドライン → 撮影などに関するガイドライン
- 発言に関するガイドライン → チャットなどに関するガイドライン

追加で修正すべき項目がある場合はコメントしてください。このメッセージを更新します。

**Comment by expacraft** [comment]
・policys→policies
・鉄道敷設に関するガイドライン → 鉄道・道路敷設に関するガイドライン
・撮影・動画配信に関するガイドライン → 撮影などに関するガイドライン
・発言に関するガイドライン → チャットなどに関するガイドライン
追加
・サービス仕様→サーバ仕様

**Comment by Hiratake** [comment]
> 撮影などに関するガイドライン
> チャットなどに関するガイドライン

「など」っていう語句を入れると、色々曖昧になってしまうし、何でもかんでも同じページに詰め込めるようになってしまうので、極力いれないほうがいいと思うので、「など」は消したいと思うんですけどどうですか。

**Comment by book000** [comment]
たしかに

**Comment by Hiratake** [comment]
![image](https://user-images.githubusercontent.com/23224932/113430622-739fab00-9415-11eb-88d3-8f5ba3f0ad6f.png)
こう？

**Comment by book000** [comment]
かな

**Comment by Hiratake** [comment]
「方針」の中身、プライバシーポリシーだけ「○○方針」じゃないの気になるとかある？
（「個人情報保護方針」だとなんか堅苦しすぎてアレだけど）

**Comment by Hiratake** [comment]
どっちでもいいか

**Comment by book000** [comment]
プライバシーポリシーはプライバシーポリシーだし個人情報保護方針だとなあだし構わんでしょ

**Comment by Hiratake** [comment]
各種処罰方針って「各種」いる？

**Comment by book000** [comment]
うーーーーーーーーーん。正直どっちでもいい

**Comment by Hiratake** [comment]
そっかdocsのほうも直さないといけないのか

**Comment by book000** [comment]
docsも反映されていそうなのでクローズします。変更するべき点あればdocsの方にissue立ててください
