### ISSUE TITLE
運営吹き出しに謎の線が表示されている

### ISSUE THREAD

**Issue by kinoko2k** [jaoafa/jaoweb#176]
### 不具合の説明

```markdown
吹き出しに謎の線が入っている。多分メロンパンからの更新でなった不具合。
```

### 再現手順

```markdown
1. jaoafa.comに飛ぶ
```

### スクリーンショット

```markdown
https://gyazo.com/deb117546ef0996861b85cfecff57915
```

**Comment by Hiratake** [comment]
Windows10のFirefox（100.0b6）、Google Chrome（100.0.4896.127）で確認しましたが、私の環境では現象が確認できませんでした。
使用した環境を教えてもらえますか？

> 多分メロンパンからの更新

Discordの `#announcement` チャンネルの件だったら、それはブラウザの開発者ツールで書き換えてるだけだから、公開しているサイトのコードは一切触っていないです。

**Comment by kinoko2k** [comment]
Win10のFloorp(8.6.2)(Firefox土台)です。

**Comment by Omuretsu** [comment]
MacOS12.3のSafari(17613.1.17.1.6)、およびChrome(104.0.5112.79)にて同様の事象を確認しました。
恒常的に不具合が発生しているわけではなくて、ページの拡大/縮小を行うと、点線が出たり消えたりするようです。
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/75904606/184347404-e2104915-5547-4474-b7e6-c3b9c3e71068.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/75904606/184347429-8d4ffeda-6dbd-44d2-b0aa-38c9617b7f9a.png">

**Comment by Hiratake** [comment]
原因はなんとなくわかりますが、解消にはデザインの変更が必要になるのでやりたくありません。
一般的に拡大縮小を頻繁に行うことは無いと思われること、Floorpなるブラウザの利用割合が少なく一般的なものではないこと、表示が崩れていることによりウェブサイトに掲載している情報が読み取れないという状態にはなっていないことから、急ぎの対応は必要ないという認識です。

いつかきっと行われるであろうウェブサイト作り直しに期待してください。（そのとき考慮します。たぶん。）
本issueはクローズさせていただきます。

**Comment by Omuretsu** [comment]
> 一般的に拡大縮小を頻繁に行うことは無いと思われること、Floorpなるブラウザの利用割合が少なく一般的なものではないこと、表示が崩れていることによりウェブサイトに掲載している情報が読み取れないという状態にはなっていないことから、急ぎの対応は必要ないという認識です。

妥当な判断だと思います。

**Comment by Hiratake** [comment]
やろ😎
