### ISSUE TITLE
コミュニティにGitHubのページが欲しいです。

### ISSUE THREAD

**Issue by kinoko2k** [jaoafa/jaoweb#214]
### 内容

https://github.com/jaoafa/jaoweb-docs#%E3%82%B3%E3%83%9F%E3%83%A5%E3%83%8B%E3%83%86%E3%82%A3
ここにGitHubもコミュニティだと思います。
https://gyazo.com/3c0ab639b4be81072121d4437bf47718

**Comment by Hiratake** [comment]
GitHubは開発者向けであり、一般のマイクラユーザー向けのものではないと思ってます。
マイクラ鯖のウェブサイトのコミュニティのところに掲載するのは、個人的には不適切と考えます。

**Comment by Hiratake** [comment]
> ここにGitHubもコミュニティだと思います。

ウェブサイトの「コミュニティ」にGitHubへのリンクを追加してほしい、という内容だという理解なんだけど、良く読んだらよくわからんわね
あってる？

**Comment by kinoko2k** [comment]
> > ここにGitHubもコミュニティだと思います。
> 
> ウェブサイトの「コミュニティ」にGitHubへのリンクを追加してほしい、という内容だという理解なんだけど、良く読んだらよくわからんわね あってる？

自分の文の動詞飛んで行ってます。
解釈あってます。


> GitHubは開発者向けであり、一般のマイクラユーザー向けのものではないと思ってます。 マイクラ鯖のウェブサイトのコミュニティのところに掲載するのは、個人的には不適切と考えます。

たしかに

**Comment by Omuretsu** [comment]
私もヒラタケさんと同じく、WebサイトにGitHubのリンクは追加する必要はないと思います。
GitHubは開発者向けのコミュニティであることや、開発やGitHubに関する情報はDiscord`#development`にて公開しているためです。

**Comment by book000** [comment]
うえにおなじ。

**Comment by Hiratake** [comment]
それでは追加なしでこのissueは閉じさせていただきもうす
