### ISSUE TITLE
外部から/server以下にアクセスするとエラーが表示される

### ISSUE THREAD

**Issue by expacraft** [jaoafa/jaoweb#25]
サイト内のリンク以外から`/server/`以下にアクセスすると、`/server/specifications`にリダイレクトされて、以下のようなエラーが表示される。
![jaoafacom2](https://user-images.githubusercontent.com/75877469/114710286-7f219900-9d68-11eb-9641-d0b9b0b5ff93.PNG)

**Comment by Hiratake** [comment]
以前のURLにアクセスした際に新しいページにリダイレクトするように設定したときに、サーバ情報のページ `/server` を新しい `/server/specifications` に移動するとかしてたのをけしました

**Comment by Hiratake** [comment]
そもそも `server` 内に `index.md` なくない？
