### ISSUE TITLE
ナビゲーションバーの「サーバ情報」にDynmapリンクを置く？

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb#26]
Webサイトからマップにアクセスする手段が結構めんどいので、ナビゲーションバーにリンクを置いてほしいかもしれない (と要望を受けました)

**Comment by Hiratake** [comment]
「コミュニティ」より「サーバ情報」じゃない？

**Comment by book000** [comment]
たしかにそうだな…サーバ情報項目多すぎてごちゃごちゃ感すごいけど。
