### ISSUE TITLE
一部ブログ記事の旧URLからのリダイレクト先修正

### ISSUE THREAD

**Issue by expacraft** [jaoafa/jaoweb#28]
旧URLから解説系記事に飛んだ時、`◯◯_commentary`の方に飛んで404になるので、`◯◯-commentary`に修正してほしい

`https://jaoafa.com/blog/worldguard_commentary` ➔ `https://jaoafa.com/blog/worldguard-commentary`
`https://jaoafa.com/blog/worldedit_commentary` ➔ `https://jaoafa.com/blog/worldedit-commentary`
`https://jaoafa.com/blog/worldeditcui_commentary` ➔ `https://jaoafa.com/blog/worldeditcui-commentary`

**Comment by Hiratake** [comment]
なおしました。
