### ISSUE TITLE
ピリオドマッチランキングページの追加

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb#32]
従来 `https://jaoafa.com/p/` にあったピリオドマッチのランキングページを作成する
jaoapi-v2にAPIを作って、APIとの通信で情報取得→表示。

`/p/` に置くべきか、 `/community/p` とかに置くべきか、それともそれ以外かなど意見貰えたら。
ある程度決まった時点で私が作ってプルリクします

**Comment by Hiratake** [comment]
communityでいいと思うけど、pってなんかページ番号みがあるから略さなくていいんじゃね

**Comment by book000** [comment]
`/community/period` ?

**Comment by Hiratake** [comment]
イイン・ジェーン

**Comment by book000** [comment]
https://jaoafa.com/data/ranking/periodmatch/ にて実装
