### ISSUE TITLE
自治体一覧ページの作成

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb#33]
運営が承認し現在運用されている自治体の一覧を表示するページを作成。

デザインが思いついてなくて普通にテーブルでつくってしまいそうなので、もしデザイン案があれば。

システムとしてはjaoapi-v2にAPIをつくり、クライアントサイドでAPI通信→データ処理

**Comment by Hiratake** [comment]
jaopediaに自治体一覧が存在しているから被らない？
https://wiki.jaoafa.com/jao_Minecraft_Server%E3%81%AE%E8%87%AA%E6%B2%BB%E4%BD%93%E4%B8%80%E8%A6%A7

**Comment by book000** [comment]
基本的に私の考えでは、jaopediaはユーザーが編集するものであるから運営が承認してデータベースとして管理しているものは `jaoafa.com` ドメイン下で明示的に表記したほうが良い気がするんだよな

**Comment by book000** [comment]
https://jaoafa.com/data/cities にて実装
