### ISSUE TITLE
トップページにあるスタッフ一覧の並び順を変更してほしい

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/jaoweb#82]
他鯖行った時に鯖管に間違われる可能性があってやだ

**Comment by Hiratake** [comment]
@kohonayoshi 
以下箇所を希望の順番に並び替えてプルリクエストを出していただけますか。
https://github.com/jaoafa/jaoweb/blob/master/pages/index.vue#L110

もしくは、変更案をこのissueに記載してください。

**Comment by kohonayoshi** [comment]
https://github.com/jaoafa/jaoweb/pull/83
プルリク多分送りました。時間があったらこういう感じにしませんか？
![image](https://user-images.githubusercontent.com/52349485/131087135-8af9bf04-3bc0-4474-8958-0bb4591b4f56.png)

**Comment by Hiratake** [comment]
> プルリク多分送りました。

後ほど確認いたします。

> 時間があったらこういう感じにしませんか？

別でissue立てていただいてもよろしいですか？
